name: Code Style
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - '*'
            - '*/*'

jobs:
    cs:
        if: github.event_name != 'schedule'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Run CS
              uses: shopware/github-actions/extension-verifier@dad4f02d83cd8d75f48272ab6eae22b480858efc # main
              with:
                  action: format

    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                version-selection: [ 'lowest', 'highest']
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Run Check
              uses: shopware/github-actions/extension-verifier@dad4f02d83cd8d75f48272ab6eae22b480858efc # main
              with:
                  action: check
                  check-against: ${{ matrix.version-selection }}
